name: FurnitureEngine
version: 1.6.2
main: com.mira.furnitureengine.FurnitureEngine
author: Mira
api-version: 1.16
description: Allows you to make custom usable furniture.
load: STARTUP
softdepend: [GSit]

commands:
  furnitureengine:
   description: Main Plugin command.
   aliases: [fe]
   permission: furnitureengine.admin

permissions:
  furnitureengine.blockbreak:
   default: true
  furnitureengine.blockplace:
   default: true
  furnitureengine.admin:
   default: op
  furnitureengine.*:
   default: op
   children:
     furnitureengine.admin: true
     furnitureengine.blockbreak: true
     furnitureengine.blockplace: true